# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_PCI_EXYNOS_GS) += pcie-exynos-gs.o
pcie-exynos-gs-objs += pcie-exynos-rc.o pcie-exynos-dbg.o
obj-$(CONFIG_PCI_EXYNOS_CAL_GS101) += pcie-exynos-gs101-rc-cal.o

ccflags-y += -I $(srctree)/drivers/pci/controller/dwc

