# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_AUDIOMETRICS)		+= amplifiers/audiometrics/
obj-$(CONFIG_SND_SOC_CS35L41)		+= amplifiers/cs35l41/
obj-$(CONFIG_HAPTICS_CS40L2X)		+= amplifiers/cs40l25/
obj-$(CONFIG_INPUT_DRV2624_HAPTICS)	+= amplifiers/drv2624/
obj-$(CONFIG_AOC_DRIVER)		+= aoc/ aoc/alsa/ aoc/usb/
obj-$(CONFIG_NITROUS)			+= bluetooth/broadcom/
obj-$(CONFIG_GOOGLE_BMS)		+= bms/
obj-$(CONFIG_DRM_SAMSUNG)		+= display/samsung/
obj-$(CONFIG_ABROLHOS)			+= edgetpu/drivers/edgetpu/
obj-$(CONFIG_FPC_FINGERPRINT)		+= fingerprint/fpc/
obj-$(CONFIG_MALI_MIDGARD)		+= gpu/mali_kbase/
obj-$(CONFIG_MALI_MEMORY_GROUP_MANAGER)	+= gpu/mali_pixel/
obj-$(CONFIG_LWIS)			+= lwis/
obj-$(CONFIG_NFC_ST21NFC)		+= nfc/
obj-$(CONFIG_POWER_RESET_EXYNOS)	+= power/reset/
obj-$(CONFIG_TOUCHSCREEN_COMMON)	+= touch/common/
obj-$(CONFIG_TOUCHSCREEN_FTS)		+= touch/fts_touch/ftm5/
obj-$(CONFIG_TOUCHSCREEN_SEC_TS)	+= touch/sec_touch/
obj-$(CONFIG_QORVO_UWB)			+= uwb/kernel/
obj-$(CONFIG_WLAN_BCM43752)		+= wlan/bcmdhd/bcm43752/
obj-$(CONFIG_WLAN_BCM4389)		+= wlan/bcmdhd/bcm4389/
