# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_AUDIOMETRICS)		+= amplifiers/audiometrics/
obj-$(CONFIG_SND_SOC_CS35L41)		+= amplifiers/cs35l41/
obj-$(CONFIG_HAPTICS_CS40L2X)		+= amplifiers/cs40l25/
obj-$(CONFIG_INPUT_DRV2624_HAPTICS)	+= amplifiers/drv2624/
obj-$(CONFIG_AOC_DRIVER)		+= aoc/ aoc/alsa/ aoc/usb/
